export type Locale = 'en' | 'zh';

export type LocalizedText = {
  en: string;
  zh: string;
};

export type MenuItem = {
  id: string;
  name: LocalizedText;
  detail: LocalizedText;
  price: number;
  kind: 'treatment' | 'package';
};

export type AddOn = {
  id: string;
  name: LocalizedText;
  price: number;
};

export type Category = {
  id: string;
  number: string;
  name: LocalizedText;
  intro: LocalizedText;
  treatments: MenuItem[];
  packages: MenuItem[];
  addOns: AddOn[];
};

export type GuestSelection = {
  id: string;
  name: string;
  categoryId: string;
  itemId: string;
  addOnIds: string[];
  therapistPreference: string;
};

export const business = {
  name: 'Serene Family Massage',
  whatsappNumber: '6589160743', // International format without the leading plus sign.
  hours: {
    en: 'Open daily · 11:00 AM–11:59 PM',
    zh: '每天营业 · 上午 11:00–晚上 11:59',
  },
  address: {
    en: 'Shop address to be added',
    zh: '店铺地址待补充',
  },
} as const;

// Demo-only estimates. Replace these values with confirmed shop operations
// before the website accepts live bookings.
export const bookingSettings = {
  firstTime: '11:00',
  lastTime: '23:30',
  closingTime: '23:59',
  intervalMinutes: 30,
  minimumLeadMinutes: 60,
  estimatedTherapists: 6,
  receptionists: 1,
  massageBeds: 6,
  footMassageChairs: 6,
  maximumConcurrentCustomers: 6,
  turnaroundMinutes: 5,
  estimatedBusyTherapistsByTime: {
    '12:00': 2,
    '12:30': 2,
    '13:00': 6,
    '13:30': 6,
    '14:00': 3,
    '14:30': 3,
    '15:00': 5,
    '15:30': 5,
    '18:30': 6,
    '19:00': 5,
    '19:30': 5,
    '20:00': 3,
  },
  estimatedItemDurationMinutes: {
    'aroma-60': 60,
    'aroma-90': 90,
    'aroma-120': 120,
    'aroma-pkg-ear': 110,
    'aroma-pkg-cupping': 115,
    'aroma-pkg-guasha': 115,
    'aroma-pkg-foot': 120,
    'thai-60': 60,
    'thai-90': 90,
    'thai-120': 120,
    'thai-pkg-cupping': 85,
    'thai-pkg-guasha': 85,
    'thai-pkg-foot': 120,
    'thai-pkg-ear': 110,
    'thai-pkg-scrub': 90,
    'body-30': 30,
    'body-60': 60,
    'body-90': 90,
    'body-120': 120,
    'body-pkg-cupping': 85,
    'body-pkg-guasha': 85,
    'body-pkg-foot': 120,
    'body-pkg-ear': 110,
    'body-pkg-scrub': 90,
    'foot-30': 30,
    'foot-60': 60,
    'foot-90': 90,
    'foot-120': 120,
    'foot-pkg-scrub': 70,
    'foot-pkg-cupping': 85,
    'foot-pkg-shoulder': 90,
    'foot-pkg-body-30': 90,
    'foot-pkg-body-first': 90,
    'foot-pkg-body-60': 120,
  },
  estimatedAddOnDurationMinutes: {
    'herbal-bag': 20,
    'thai-balm': 0,
    'coconut-oil': 0,
    'aroma-oil': 0,
    'ear-candling': 20,
    'foot-scrubbing': 10,
    'gua-sha': 25,
    'cupping': 25,
    'fire-cupping': 25,
    'bleeding-cupping': 30,
    'body-scrubbing': 30,
    'shoulder-15': 15,
    'shoulder-30': 30,
  },
} as const;

const duration = (id: string, en: string, zh: string, price: number): MenuItem => ({
  id,
  name: { en, zh },
  detail: { en: 'Massage session', zh: '按摩疗程' },
  price,
  kind: 'treatment',
});

const bundle = (id: string, en: string, zh: string, price: number): MenuItem => ({
  id,
  name: { en, zh },
  detail: { en: 'Value package', zh: '优惠配套' },
  price,
  kind: 'package',
});

const addOn = (id: string, en: string, zh: string, price: number): AddOn => ({
  id,
  name: { en, zh },
  price,
});

export const catalog: Category[] = [
  {
    id: 'aromatherapy',
    number: '01',
    name: { en: 'Aromatherapy Body Massage', zh: '精油全身按摩' },
    intro: {
      en: 'A soothing full-body ritual with your choice of aromatic oil.',
      zh: '自选芳香精油，享受舒缓放松的全身按摩。',
    },
    treatments: [
      duration('aroma-60', '1 hour', '1 小时', 85),
      duration('aroma-90', '90 minutes', '1 小时半', 125),
      duration('aroma-120', '2 hours', '2 小时', 150),
    ],
    addOns: [
      addOn('ear-candling', 'Ear candling', '耳烛', 20),
      addOn('gua-sha', 'Gua Sha', '刮痧', 35),
      addOn('cupping', 'Cupping', '拔罐', 35),
      addOn('fire-cupping', 'Fire cupping', '拔火罐', 45),
      addOn('bleeding-cupping', 'Bleeding cupping', '放血罐', 55),
      addOn('body-scrubbing', 'Body scrubbing', '全身海盐磨砂', 55),
    ],
    packages: [
      bundle('aroma-pkg-ear', '90 min aromatherapy + ear candling', '1 小时半精油全身按摩 + 耳烛', 140),
      bundle('aroma-pkg-cupping', '90 min aromatherapy + cupping', '1 小时半精油全身按摩 + 拔罐', 150),
      bundle('aroma-pkg-guasha', '90 min aromatherapy + Gua Sha', '1 小时半精油全身按摩 + 刮痧', 150),
      bundle('aroma-pkg-foot', '1 hour aromatherapy + 1 hour foot massage', '1 小时精油全身按摩 + 1 小时足部按摩', 125),
    ],
  },
  {
    id: 'thai',
    number: '02',
    name: { en: 'Traditional Thai Massage', zh: '泰式全身按摩' },
    intro: {
      en: 'Traditional pressure and stretching techniques for a lighter, looser body.',
      zh: '结合传统按压与拉伸手法，舒展身体、释放紧绷。',
    },
    treatments: [
      duration('thai-60', '1 hour', '1 小时', 80),
      duration('thai-90', '90 minutes', '1 小时半', 110),
      duration('thai-120', '2 hours', '2 小时', 140),
    ],
    addOns: [
      addOn('thai-balm', 'Thai balm', '泰风油', 8),
      addOn('ear-candling', 'Ear candling', '耳烛', 20),
      addOn('gua-sha', 'Gua Sha', '刮痧', 35),
      addOn('cupping', 'Cupping', '拔罐', 35),
      addOn('fire-cupping', 'Fire cupping', '拔火罐', 45),
      addOn('bleeding-cupping', 'Bleeding cupping', '放血罐', 55),
      addOn('body-scrubbing', 'Body scrubbing', '全身海盐磨砂', 55),
    ],
    packages: [
      bundle('thai-pkg-cupping', '1 hour Thai massage + cupping', '1 小时泰式全身按摩 + 拔罐', 105),
      bundle('thai-pkg-guasha', '1 hour Thai massage + Gua Sha', '1 小时泰式全身按摩 + 刮痧', 105),
      bundle('thai-pkg-foot', '1 hour Thai massage + 1 hour foot massage', '1 小时泰式全身按摩 + 1 小时足部按摩', 120),
      bundle('thai-pkg-ear', '90 min Thai massage + ear candling', '1 小时半泰式全身按摩 + 耳烛', 120),
      bundle('thai-pkg-scrub', '1 hour Thai massage + body scrubbing', '1 小时泰式全身按摩 + 全身海盐磨砂', 125),
    ],
  },
  {
    id: 'full-body',
    number: '03',
    name: { en: 'Full Body Massage', zh: '全身按摩' },
    intro: {
      en: 'A classic head-to-toe massage, tailored to the time you have.',
      zh: '经典全身按摩，按您的时间灵活选择疗程长度。',
    },
    treatments: [
      duration('body-30', '30 minutes', '30 分钟', 45),
      duration('body-60', '1 hour', '1 小时', 68),
      duration('body-90', '90 minutes', '1 小时半', 100),
      duration('body-120', '2 hours', '2 小时', 130),
    ],
    addOns: [
      addOn('thai-balm', 'Thai balm', '泰风油', 8),
      addOn('coconut-oil', 'Coconut oil', '椰油', 10),
      addOn('aroma-oil', 'Aroma oil', '芳香按摩油', 15),
      addOn('ear-candling', 'Ear candling', '耳烛', 20),
      addOn('gua-sha', 'Gua Sha', '刮痧', 35),
      addOn('cupping', 'Cupping', '拔罐', 35),
      addOn('fire-cupping', 'Fire cupping', '拔火罐', 45),
      addOn('bleeding-cupping', 'Bleeding cupping', '放血罐', 55),
      addOn('body-scrubbing', 'Body scrubbing', '全身海盐磨砂', 55),
    ],
    packages: [
      bundle('body-pkg-cupping', '1 hour body massage + cupping', '1 小时全身按摩 + 拔罐', 95),
      bundle('body-pkg-guasha', '1 hour body massage + Gua Sha', '1 小时全身按摩 + 刮痧', 95),
      bundle('body-pkg-foot', '1 hour body massage + 1 hour foot massage', '1 小时全身按摩 + 1 小时足部按摩', 110),
      bundle('body-pkg-ear', '90 min body massage + ear candling', '1 小时半全身按摩 + 耳烛', 110),
      bundle('body-pkg-scrub', '1 hour body massage + body scrubbing', '1 小时全身按摩 + 全身海盐磨砂', 115),
    ],
  },
  {
    id: 'foot',
    number: '04',
    name: { en: 'Foot Massage', zh: '足部按摩' },
    intro: {
      en: 'Focused care for tired feet, with easy add-ons for shoulders or body.',
      zh: '专注舒缓疲惫双足，并可轻松搭配肩颈或全身按摩。',
    },
    treatments: [
      duration('foot-30', '30 minutes', '30 分钟', 38),
      duration('foot-60', '1 hour', '1 小时', 50),
      duration('foot-90', '90 minutes', '1 小时半', 75),
      duration('foot-120', '2 hours', '2 小时', 98),
    ],
    addOns: [
      addOn('herbal-bag', 'Herbal foot bath bag', '草药足浴包', 8),
      addOn('thai-balm', 'Thai balm', '泰风油', 8),
      addOn('coconut-oil', 'Coconut oil', '椰油', 10),
      addOn('ear-candling', 'Ear candling', '耳烛', 20),
      addOn('foot-scrubbing', 'Foot scrubbing', '足部磨砂', 20),
      addOn('gua-sha', 'Gua Sha', '刮痧', 35),
      addOn('cupping', 'Cupping · foot or body', '拔罐 · 足部或身体', 35),
      addOn('fire-cupping', 'Fire cupping · foot or body', '拔火罐 · 足部或身体', 45),
      addOn('shoulder-15', 'Shoulder massage · 15 min', '肩部按摩 · 15 分钟', 20),
      addOn('shoulder-30', 'Shoulder massage · 30 min', '肩部按摩 · 30 分钟', 40),
    ],
    packages: [
      bundle('foot-pkg-scrub', '1 hour foot massage + foot scrubbing', '1 小时足部按摩 + 足部磨砂', 65),
      bundle('foot-pkg-cupping', '1 hour foot massage + foot cupping', '1 小时足部按摩 + 足部拔罐', 80),
      bundle('foot-pkg-shoulder', '1 hour foot massage + 30 min shoulder massage', '1 小时足部按摩 + 30 分钟肩部按摩', 85),
      bundle('foot-pkg-body-30', '1 hour foot massage + 30 min body massage', '1 小时足部按摩 + 30 分钟全身按摩', 85),
      bundle('foot-pkg-body-first', '1 hour body massage + 30 min foot massage', '1 小时全身按摩 + 30 分钟足部按摩', 95),
      bundle('foot-pkg-body-60', '1 hour foot massage + 1 hour body massage', '1 小时足部按摩 + 1 小时全身按摩', 110),
    ],
  },
];

export const ui = {
  en: {
    language: 'Language',
    navMenu: 'Treatments',
    navBook: 'Book a visit',
    eyebrow: 'REST · RESTORE · RECONNECT',
    heroTitle: 'Make time for',
    heroAccent: 'feeling good.',
    heroBody: 'Thoughtful massage treatments for you and your loved ones. Choose your favourites and request a time in just a few minutes.',
    chooseTreatment: 'Choose your treatment',
    payShop: 'Deposit feature planned',
    groupBooking: 'Groups up to 6',
    staffConfirmation: 'Staff confirmation',
    treatmentsEyebrow: 'THE TREATMENT MENU',
    treatmentsTitle: 'Find your kind of calm.',
    addingTo: 'Choosing a treatment for',
    selected: 'Selected',
    selectedService: 'Selected service',
    regularSessions: 'Massage sessions',
    packages: 'Packages',
    addOns: 'Available add-ons',
    from: 'From',
    addToBooking: 'Choose this',
    bookingEyebrow: 'YOUR VISIT',
    bookingTitle: 'Build your booking.',
    bookingIntro: 'Add each guest, choose their treatment, then request one shared arrival time.',
    guests: 'Guests',
    guest: 'Guest',
    addGuest: 'Add guest',
    guestName: 'Guest name (optional)',
    treatmentType: 'Treatment type',
    selectTreatment: 'Select a treatment or package',
    extras: 'Add a little extra',
    therapist: 'Preferred therapist (optional)',
    therapistHint: 'Therapist name, male, female, or no preference',
    removeGuest: 'Remove guest',
    groupTiming: 'Group timing',
    startTogether: 'Prefer everyone to start together',
    flexibleStart: 'Flexible — staff may stagger starts or begin with a foot soak',
    appointment: 'Appointment request',
    preferredDate: 'Preferred date',
    preferredTime: 'Preferred time',
    chooseTime: 'Choose a preferred time',
    demoAvailability: 'Demo availability',
    demoAvailabilityNote: 'Estimated with 6 therapists, sample bookings, and 5 minutes for cleaning. Therapist skills and monthly rest days are not configured yet.',
    selectDateFirst: 'Choose a date to see estimated time slots.',
    selectServicesFirst: 'Choose a service for every guest to calculate available times.',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    estimatedVisit: 'Estimated visit length',
    noDemoTimes: 'No estimated times fit this booking. Try another date or shorten the group services.',
    availableLegend: 'Estimated available',
    unavailableLegend: 'Unavailable',
    timeRequestNote: 'These are demonstration estimates, not live availability. Staff must still confirm the requested time in WhatsApp.',
    contactName: 'Contact name',
    whatsappPhone: 'WhatsApp phone number',
    notes: 'Notes (optional)',
    notesHint: 'Health considerations, requests, or anything staff should know',
    summary: 'Your request',
    notSelected: 'Treatment not selected',
    subtotal: 'Subtotal',
    total: 'Estimated total',
    review: 'Review request',
    payNote: 'No payment now. Your time is not reserved until staff confirms it in WhatsApp.',
    reviewTitle: 'One last look.',
    reference: 'Reference',
    sendWhatsApp: 'Send in WhatsApp',
    sendHint: 'WhatsApp will open with your request ready. Staff will reply to confirm it or offer another time.',
    copySummary: 'Copy request',
    copied: 'Request copied',
    close: 'Close',
    configureNotice: 'The shop WhatsApp number has not been added yet. You can copy the request now; add the number in the business configuration before launch.',
    invalidForm: 'Please complete the highlighted booking details.',
    pastTime: 'Please choose a future appointment time.',
    validationRemaining: 'details need attention',
    validationIntro: 'Tap an item below to go directly to the field that needs attention.',
    missingGuestService: 'Choose a treatment or package',
    missingDate: 'Choose a preferred date',
    missingTime: 'Choose a preferred time',
    invalidContactName: 'Enter the contact name',
    invalidPhone: 'Enter a valid WhatsApp phone number',
    minimumNotice: 'Bookings require at least 1 hour notice.',
    bookingPolicy: 'Booking policy',
    policySummary: 'Arrive on time. Bookings may be cancelled after 15 minutes without advance notice. Please contact the shop early if plans change.',
    footerLine: 'A quieter moment starts here.',
    medicalNote: 'Please tell staff about pregnancy, injuries, allergies, or medical concerns before treatment. Services are subject to staff confirmation.',
    addressPending: 'Business details are ready to be replaced before launch.',
  },
  zh: {
    language: '语言',
    navMenu: '按摩疗程',
    navBook: '预约到店',
    eyebrow: '休息 · 恢复 · 重拾平衡',
    heroTitle: '给自己一点时间，',
    heroAccent: '感受身心舒畅。',
    heroBody: '为您与家人精心准备的按摩疗程。选择心仪服务，只需几分钟即可预约。',
    chooseTreatment: '选择您的疗程',
    payShop: '订金功能规划中',
    groupBooking: '最多 6 人同行',
    staffConfirmation: '店员确认预约',
    treatmentsEyebrow: '按摩疗程菜单',
    treatmentsTitle: '找到属于您的放松方式。',
    addingTo: '正在为以下客人选择疗程：',
    selected: '已选择',
    selectedService: '已选择的疗程',
    regularSessions: '按摩疗程',
    packages: '优惠配套',
    addOns: '可选附加项目',
    from: '起价',
    addToBooking: '选择此项目',
    bookingEyebrow: '您的到店安排',
    bookingTitle: '建立您的预约。',
    bookingIntro: '添加每位客人并选择疗程，然后共同选择一个希望到店的时间。',
    guests: '客人',
    guest: '客人',
    addGuest: '添加客人',
    guestName: '客人姓名（选填）',
    treatmentType: '按摩类型',
    selectTreatment: '选择按摩疗程或优惠配套',
    extras: '添加附加项目',
    therapist: '偏好按摩师（选填）',
    therapistHint: '可填写按摩师姓名、男按摩师、女按摩师或无偏好',
    removeGuest: '移除此客人',
    groupTiming: '同行客人的时间安排',
    startTogether: '希望所有客人同时开始',
    flexibleStart: '时间可灵活安排——店员可错开开始时间或先安排泡脚',
    appointment: '预约要求',
    preferredDate: '希望日期',
    preferredTime: '希望时间',
    chooseTime: '选择希望时间',
    demoAvailability: '演示可预约时间',
    demoAvailabilityNote: '目前以 6 位按摩师、示例预约和 5 分钟清洁时间估算。按摩师技能及每月休息日尚未设置。',
    selectDateFirst: '请选择日期，以查看预计可预约时间。',
    selectServicesFirst: '请先为每位客人选择疗程，系统才能计算可预约时间。',
    morning: '上午',
    afternoon: '下午',
    evening: '晚上',
    estimatedVisit: '预计到店时长',
    noDemoTimes: '没有适合此预约的预计时间，请尝试其他日期或缩短同行客人的疗程。',
    availableLegend: '预计可预约',
    unavailableLegend: '不可预约',
    timeRequestNote: '这些仅为产品演示估算，并非实时空位。所选时间仍须由店员通过 WhatsApp 确认。',
    contactName: '联系人姓名',
    whatsappPhone: 'WhatsApp 手机号码',
    notes: '备注（选填）',
    notesHint: '健康注意事项、特别要求或其他需要告知店员的内容',
    summary: '您的预约要求',
    notSelected: '尚未选择疗程',
    subtotal: '小计',
    total: '预计总额',
    review: '查看预约要求',
    payNote: '现在无需付款。所选时间在店员通过 WhatsApp 确认前并未保留。',
    reviewTitle: '最后确认。',
    reference: '参考编号',
    sendWhatsApp: '通过 WhatsApp 发送',
    sendHint: 'WhatsApp 将打开并显示您的预约要求。店员会回复确认，或建议其他时间。',
    copySummary: '复制预约要求',
    copied: '已复制预约要求',
    close: '关闭',
    configureNotice: '尚未添加店铺 WhatsApp 号码。您可以先复制预约要求；正式发布前请在商家设置中添加号码。',
    invalidForm: '请填写标记的预约资料。',
    pastTime: '请选择未来的预约时间。',
    validationRemaining: '项需要检查',
    validationIntro: '点击以下项目，即可直接前往需要填写或修改的位置。',
    missingGuestService: '请选择按摩疗程或优惠配套',
    missingDate: '请选择希望日期',
    missingTime: '请选择希望时间',
    invalidContactName: '请输入联系人姓名',
    invalidPhone: '请输入有效的 WhatsApp 手机号码',
    minimumNotice: '预约必须至少提前 1 小时。',
    bookingPolicy: '预约须知',
    policySummary: '请准时到店。若迟到超过 15 分钟且未提前通知，预约可能会自动取消。如行程有变，请尽早联系店铺。',
    footerLine: '宁静时光，由此开始。',
    medicalNote: '如有怀孕、受伤、过敏或健康疑虑，请在疗程前告知店员。所有服务以店员确认为准。',
    addressPending: '商家资料可在正式发布前替换。',
  },
} as const;
